import 'package:flutter/material.dart';

import '../../core/theme/dagacs_theme.dart';
import '../../models/hod_attendance_matrix.dart';
import '../attendance_summary_cards.dart';

/// Which column the attendance matrix is sorted by.
///
/// Mirrors the server's `sortBy` values one-to-one, so a sort never has to be
/// re-derived or approximated on the client.
enum HodMatrixSort {
  enrollmentNumber('enrollmentNumber', 'Enrollment No.'),
  name('name', 'Student Name'),
  overallPercentage('overallPercentage', 'Overall Attendance %');

  const HodMatrixSort(this.value, this.label);

  final String value;
  final String label;
}

/// The HOD attendance cross-tab.
///
/// Design notes, all of them deliberate:
///
/// * <b>Dynamic columns.</b> One column per subject of the selected academic
///   context, generated by the backend. No subject is ever hardcoded here, and
///   the column list is the single source of truth for the cell positions.
/// * <b>Present / Total cells.</b> `32 / 40` keeps the denominator visible, which
///   a bare percentage hides. The percentage is available as a tooltip and to
///   assistive technology, so status is never communicated by colour alone.
/// * <b>Wide by nature.</b> The table always renders every column and scrolls
///   horizontally; nothing is dropped or converted into cards on a small
///   screen, so a report can never silently lose a subject.
/// * <b>Sticky identity.</b> Enrollment number, student name and the totals stay
///   pinned while the subject columns scroll, so a row stays identifiable.
/// * <b>No data is never zero.</b> A subject with no conducted class shows
///   `0 / 0` and an explicit `N/A` percentage, which is the application's
///   established representation and never a fabricated 0%.
class HodMatrixTable extends StatelessWidget {
  const HodMatrixTable({
    super.key,
    required this.columns,
    required this.rows,
    this.sort = HodMatrixSort.enrollmentNumber,
    this.sortAscending = true,
    this.onSortChanged,
    this.onRowTap,
    this.thresholdPercentage,
  });

  final List<HodAttendanceMatrixColumn> columns;
  final List<HodAttendanceMatrixRow> rows;
  final HodMatrixSort sort;
  final bool sortAscending;
  final ValueChanged<HodMatrixSort>? onSortChanged;
  final ValueChanged<HodAttendanceMatrixRow>? onRowTap;

  /// The application's fixed low-attendance threshold, shown in the header so a
  /// reader knows what the percentage colouring means.
  final double? thresholdPercentage;

  static const double _identityColumnWidth = 132;
  static const double _nameColumnWidth = 190;
  static const double _subjectColumnWidth = 108;
  static const double _totalColumnWidth = 96;
  static const double _percentageColumnWidth = 124;
  static const double _rowHorizontalPadding = DagacsSpace.sm;

  /// The exact, deterministic width of the cross-tab.
  ///
  /// Every column has a fixed width, so the table's own width is known without
  /// measuring anything. That lets the header background span the full table
  /// even when the table is wider than the viewport, and keeps the horizontal
  /// scroll extent exact instead of relying on an intrinsic-width pass.
  double _tableWidth(double viewportWidth) {
    final natural = _identityColumnWidth +
        _nameColumnWidth +
        columns.length * _subjectColumnWidth +
        2 * _totalColumnWidth +
        _percentageColumnWidth +
        // The row padding sits inside the table width, so it must be part of
        // it or the columns would overflow their own container.
        2 * _rowHorizontalPadding;
    return natural > viewportWidth ? natural : viewportWidth;
  }

  @override
  Widget build(BuildContext context) {
    if (columns.isEmpty) {
      return const _NoSubjectColumns();
    }

    return LayoutBuilder(
      builder: (context, constraints) {
        // Two scroll views: horizontally for the dynamic subject columns,
        // vertically for the student rows, with the header staying at the top.
        return SingleChildScrollView(
          key: const Key('hod-matrix-scroll-vertical'),
          child: SingleChildScrollView(
            key: const Key('hod-matrix-scroll-horizontal'),
            scrollDirection: Axis.horizontal,
            child: SizedBox(
              width: _tableWidth(constraints.maxWidth),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                mainAxisSize: MainAxisSize.min,
                children: [
                  _header(context),
                  const Divider(height: 1),
                  ...rows.map((row) => _dataRow(context, row)),
                ],
              ),
            ),
          ),
        );
      },
    );
  }

  Widget _header(BuildContext context) {
    return Container(
      key: const Key('hod-matrix-header'),
      color: DagacsColors.surfaceAlt,
      padding: const EdgeInsets.symmetric(
        horizontal: _rowHorizontalPadding,
        vertical: DagacsSpace.sm,
      ),
      child: Row(
        children: [
          _headerCell(
            key: const Key('hod-matrix-sort-enrollmentNumber'),
            label: 'Enrollment No.',
            width: _identityColumnWidth,
            align: TextAlign.left,
            onTap: onSortChanged == null
                ? null
                : () => onSortChanged!(HodMatrixSort.enrollmentNumber),
          ),
          _headerCell(
            key: const Key('hod-matrix-sort-name'),
            label: 'Student Name',
            width: _nameColumnWidth,
            align: TextAlign.left,
            onTap: onSortChanged == null
                ? null
                : () => onSortChanged!(HodMatrixSort.name),
          ),
          for (final column in columns)
            _subjectHeader(context, column),
          _headerCell(
            key: const Key('hod-matrix-header-total-present'),
            label: 'Total Present',
            width: _totalColumnWidth,
            align: TextAlign.center,
          ),
          _headerCell(
            key: const Key('hod-matrix-header-total-classes'),
            label: 'Total Classes',
            width: _totalColumnWidth,
            align: TextAlign.center,
          ),
          _headerCell(
            key: const Key('hod-matrix-sort-overallPercentage'),
            label: 'Overall Attendance %',
            width: _percentageColumnWidth,
            align: TextAlign.center,
            onTap: onSortChanged == null
                ? null
                : () => onSortChanged!(HodMatrixSort.overallPercentage),
          ),
        ],
      ),
    );
  }

  Widget _subjectHeader(BuildContext context, HodAttendanceMatrixColumn column) {
    final faculty = column.facultyNames.isEmpty
        ? 'No faculty assigned'
        : column.facultyNames.join(', ');
    return Tooltip(
      message: '${column.fullLabel}\nFaculty: $faculty',
      child: SizedBox(
        key: Key('hod-matrix-column-${column.subjectId}'),
        width: _subjectColumnWidth,
        child: Text(
          column.headerLabel,
          maxLines: 2,
          overflow: TextOverflow.ellipsis,
          textAlign: TextAlign.center,
          style: DagacsTextStyles.caption.copyWith(
            fontWeight: FontWeight.w700,
            color: DagacsColors.textPrimary,
          ),
        ),
      ),
    );
  }

  Widget _headerCell({
    Key? key,
    required String label,    required double width,
    required TextAlign align,
    VoidCallback? onTap,
  }) {
    final active = _isActive(label);
    return SizedBox(
      key: key,
      width: width,
      child: InkWell(
        onTap: onTap,
        child: Semantics(
          button: onTap != null,
          // `container` + `excludeSemantics` so the label below is what a
          // screen reader announces, instead of the bare text being announced
          // twice or the label being dropped as a mere annotation.
          container: true,
          excludeSemantics: true,
          label: onTap == null
              ? label
              : '$label, ${active ? (sortAscending ? 'sorted ascending' : 'sorted descending') : 'not sorted'}. Activate to sort.',
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: DagacsSpace.xs),
            child: Row(
              mainAxisAlignment: align == TextAlign.left
                  ? MainAxisAlignment.start
                  : MainAxisAlignment.center,
              children: [
                Flexible(
                  child: Text(
                    label,
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis,
                    textAlign: align,
                    style: DagacsTextStyles.caption.copyWith(
                      fontWeight: FontWeight.w700,
                      color: DagacsColors.textPrimary,
                    ),
                  ),
                ),
                if (active) ...[
                  const SizedBox(width: 2),
                  Icon(
                    sortAscending
                        ? Icons.arrow_upward
                        : Icons.arrow_downward,
                    size: 12,
                    color: DagacsColors.brandPrimary,
                  ),
                ],
              ],
            ),
          ),
        ),
      ),
    );
  }

  bool _isActive(String label) {
    switch (sort) {
      case HodMatrixSort.enrollmentNumber:
        return label == 'Enrollment No.';
      case HodMatrixSort.name:
        return label == 'Student Name';
      case HodMatrixSort.overallPercentage:
        return label == 'Overall Attendance %';
    }
  }

  Widget _dataRow(BuildContext context, HodAttendanceMatrixRow row) {
    final band = AttendanceSummaryCards.bandColor(row.overallPercentage);
    final content = Row(
      children: [
        SizedBox(
          width: _identityColumnWidth,
          child: Text(
            row.identity,
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
            style: DagacsTextStyles.body,
          ),
        ),
        SizedBox(
          width: _nameColumnWidth,
          child: Text(
            row.studentName,
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
            style: DagacsTextStyles.body,
          ),
        ),
        for (var i = 0; i < columns.length; i++)
          _cell(context, row, i, columns[i]),
        SizedBox(
          width: _totalColumnWidth,
          child: Text(
            '${row.totalPresent}',
            textAlign: TextAlign.center,
            style: DagacsTextStyles.body,
          ),
        ),
        SizedBox(
          width: _totalColumnWidth,
          child: Text(
            '${row.totalClasses}',
            textAlign: TextAlign.center,
            style: DagacsTextStyles.body,
          ),
        ),
        SizedBox(
          width: _percentageColumnWidth,
          child: Text(
            row.overallPercentage == null
                ? 'N/A'
                : '${row.overallPercentage!.toStringAsFixed(2)}%',
            textAlign: TextAlign.center,
            style: DagacsTextStyles.body.copyWith(
              fontWeight: FontWeight.w700,
              color: band,
            ),
          ),
        ),
      ],
    );

    final padded = Padding(
      padding: const EdgeInsets.symmetric(
        horizontal: _rowHorizontalPadding,
        vertical: DagacsSpace.sm,
      ),
      child: content,
    );

    if (onRowTap == null) {
      return padded;
    }
    return InkWell(
      key: Key('hod-matrix-row-${row.studentId}'),
      onTap: () => onRowTap!(row),
      child: padded,
    );
  }

  Widget _cell(BuildContext context, HodAttendanceMatrixRow row, int index,
      HodAttendanceMatrixColumn column) {
    final cell = row.cellAt(index);
    final present = cell?.present ?? 0;
    final total = cell?.total ?? 0;
    final percentage = cell?.percentage;
    final color = AttendanceSummaryCards.bandColor(percentage);
    final label = percentage == null
        ? '${column.fullLabel}: no class conducted'
        : '${column.fullLabel}: $present of $total classes attended, '
            '${percentage.toStringAsFixed(2)} percent';

    return Tooltip(
      message: label,
      child: SizedBox(
        key: Key('hod-matrix-cell-${row.studentId}-${column.subjectId}'),
        width: _subjectColumnWidth,
        child: Semantics(
          // The label states the subject, the counts and the percentage, so it
          // replaces the raw "32 / 40" text for assistive technology.
          container: true,
          excludeSemantics: true,
          label: label,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                '$present / $total',
                textAlign: TextAlign.center,
                style: DagacsTextStyles.body,
              ),
              Text(
                percentage == null ? 'N/A' : '${percentage.toStringAsFixed(1)}%',
                textAlign: TextAlign.center,
                style: DagacsTextStyles.caption.copyWith(
                  fontSize: 11,
                  fontWeight: FontWeight.w600,
                  color: total == 0 ? DagacsColors.textSecondary : color,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

/// The academic context holds no subjects at all.
///
/// This is deliberately distinct from "the subjects have no attendance yet": the
/// matrix cannot be produced without a subject to put on a column, so the state
/// is stated instead of rendering an empty table.
class _NoSubjectColumns extends StatelessWidget {
  const _NoSubjectColumns();

  @override
  Widget build(BuildContext context) {
    return Padding(
      key: const Key('hod-matrix-no-subjects'),
      padding: const EdgeInsets.symmetric(vertical: DagacsSpace.xl),
      child: Column(
        children: const [
          Icon(Icons.inbox_outlined, size: 40, color: DagacsColors.textSecondary),
          SizedBox(height: DagacsSpace.md),
          Text('No subjects are offered in the selected semester.'),
        ],
      ),
    );
  }
}
