import 'package:flutter/foundation.dart';

import 'hod_attendance_context.dart';

/// One student x subject cell of the HOD attendance matrix.
///
/// [total] is the number of <b>conducted classes</b> of that subject, so it is
/// the same for every student of the class and stays non-zero even when a
/// particular student was never marked. [percentage] is null only when the
/// subject had no conducted class at all — never a fabricated 0%.
@immutable
class HodAttendanceMatrixCell {
  const HodAttendanceMatrixCell({
    required this.subjectId,
    required this.present,
    required this.total,
    this.percentage,
  });

  factory HodAttendanceMatrixCell.fromJson(Map<String, dynamic> json) =>
      HodAttendanceMatrixCell(
        subjectId: (json['subjectId'] as num?)?.toInt() ?? 0,
        present: (json['present'] as num?)?.toInt() ?? 0,
        total: (json['total'] as num?)?.toInt() ?? 0,
        // Absent from the payload when null, so a missing key means "no class".
        percentage: (json['percentage'] as num?)?.toDouble(),
      );

  final int subjectId;
  final int present;
  final int total;
  final double? percentage;

  /// True when the subject had at least one conducted class.
  bool get hasConductedClass => total > 0;

  /// The canonical `Present / Total` display form used by the matrix, the
  /// detail views and the export.
  String get fraction => '$present / $total';
}

/// One dynamic subject column of the HOD attendance matrix.
///
/// Columns are generated by the backend from the selected academic context's
/// real subject offerings and teaching assignments — never from the whole
/// department. [subjectId] is the stable identifier a client keys on;
/// [subjectCode] and [subjectName] are display labels only.
@immutable
class HodAttendanceMatrixColumn {
  const HodAttendanceMatrixColumn({
    required this.subjectId,
    required this.subjectOfferingId,
    required this.subjectCode,
    required this.subjectName,
    this.facultyNames = const [],
  });

  factory HodAttendanceMatrixColumn.fromJson(Map<String, dynamic> json) =>
      HodAttendanceMatrixColumn(
        subjectId: (json['subjectId'] as num?)?.toInt() ?? 0,
        subjectOfferingId: (json['subjectOfferingId'] as num?)?.toInt(),
        subjectCode: json['subjectCode'] as String? ?? '',
        subjectName: json['subjectName'] as String? ?? '',
        facultyNames: (json['facultyNames'] as List?)
                ?.where((e) => e != null)
                .map((e) => e.toString())
                .toList(growable: false) ??
            const [],
      );

  final int subjectId;
  final int? subjectOfferingId;
  final String subjectCode;
  final String subjectName;
  final List<String> facultyNames;

  /// Short header label. The subject code is the primary identifier in an
  /// academic report; the name is the accessible tooltip.
  String get headerLabel =>
      subjectCode.isNotEmpty ? subjectCode : subjectName;

  String get fullLabel {
    if (subjectCode.isEmpty) return subjectName;
    if (subjectName.isEmpty) return subjectCode;
    return '$subjectCode · $subjectName';
  }
}

/// One student row of the HOD attendance matrix — a cross-tab row.
///
/// [subjects] has exactly one entry per column of the parent matrix, aligned by
/// position, so a client never has to look a cell up by name. A student who was
/// never marked in a single class is still present, and is measured against the
/// conducted classes like everyone else: `0 / 10 = 0%`, never `0 / 0`.
@immutable
class HodAttendanceMatrixRow {
  const HodAttendanceMatrixRow({
    required this.studentId,
    required this.enrollmentNumber,
    required this.rollNumber,
    required this.studentName,
    required this.sectionName,
    required this.subjects,
    required this.totalPresent,
    required this.totalClasses,
    this.overallPercentage,
  });

  factory HodAttendanceMatrixRow.fromJson(Map<String, dynamic> json) =>
      HodAttendanceMatrixRow(
        studentId: (json['studentId'] as num?)?.toInt() ?? 0,
        enrollmentNumber: json['enrollmentNumber'] as String? ?? '',
        rollNumber: json['rollNumber'] as String? ?? '',
        studentName: json['studentName'] as String? ?? '',
        sectionName: json['sectionName'] as String? ?? '',
        subjects: (json['subjects'] as List?)
                ?.whereType<Map>()
                .map((e) =>
                    HodAttendanceMatrixCell.fromJson(Map<String, dynamic>.from(e)))
                .toList(growable: false) ??
            const [],
        totalPresent: (json['totalPresent'] as num?)?.toInt() ?? 0,
        totalClasses: (json['totalClasses'] as num?)?.toInt() ?? 0,
        overallPercentage: (json['overallPercentage'] as num?)?.toDouble(),
      );

  final int studentId;
  final String enrollmentNumber;
  final String rollNumber;
  final String studentName;
  final String sectionName;
  final List<HodAttendanceMatrixCell> subjects;
  final int totalPresent;
  final int totalClasses;
  final double? overallPercentage;

  /// Never empty: the enrolment number is authoritative and the roll number is
  /// the fallback for legacy students.
  String get identity => enrollmentNumber.isNotEmpty ? enrollmentNumber : rollNumber;

  /// True when at least one class was conducted, so a real percentage exists.
  bool get hasConductedClasses => totalClasses > 0;

  /// The cell of the column at [index], or null when the backend and the column
  /// list ever disagree. Callers render `0 / 0` for that rather than guessing.
  HodAttendanceMatrixCell? cellAt(int index) =>
      index >= 0 && index < subjects.length ? subjects[index] : null;
}

/// The complete HOD attendance matrix for one fully-resolved academic context.
@immutable
class HodAttendanceMatrix {
  const HodAttendanceMatrix({
    required this.context,
    required this.subjects,
    required this.students,
    required this.page,
    required this.size,
    required this.totalElements,
    required this.totalPages,
    required this.singleSubject,
    this.thresholdPercentage,
  });

  factory HodAttendanceMatrix.fromJson(Map<String, dynamic> json) =>
      HodAttendanceMatrix(
        context: json['context'] is Map
            ? HodAttendanceContext.fromJson(
                Map<String, dynamic>.from(json['context'] as Map))
            : HodAttendanceContext.empty,
        subjects: (json['subjects'] as List?)
                ?.whereType<Map>()
                .map((e) => HodAttendanceMatrixColumn.fromJson(
                    Map<String, dynamic>.from(e)))
                .toList(growable: false) ??
            const [],
        students: (json['students'] as List?)
                ?.whereType<Map>()
                .map((e) =>
                    HodAttendanceMatrixRow.fromJson(Map<String, dynamic>.from(e)))
                .toList(growable: false) ??
            const [],
        page: (json['page'] as num?)?.toInt() ?? 0,
        size: (json['size'] as num?)?.toInt() ?? 0,
        totalElements: (json['totalElements'] as num?)?.toInt() ?? 0,
        totalPages: (json['totalPages'] as num?)?.toInt() ?? 0,
        singleSubject: json['singleSubject'] == true,
        thresholdPercentage: (json['thresholdPercentage'] as num?)?.toDouble(),
      );

  final HodAttendanceContext context;
  final List<HodAttendanceMatrixColumn> subjects;
  final List<HodAttendanceMatrixRow> students;
  final int page;
  final int size;
  final int totalElements;
  final int totalPages;
  final bool singleSubject;
  final double? thresholdPercentage;

  bool get isEmpty => students.isEmpty;

  /// True when the academic context holds no subjects at all, which is different
  /// from holding subjects that merely have no attendance yet.
  bool get hasNoSubjectColumns => subjects.isEmpty;

  bool get hasPreviousPage => page > 0;

  bool get hasNextPage => totalPages > 0 && page < totalPages - 1;
}
